<?php

/**
 * @file gsb_node_modal.module
 */

/**
 * Implements hook_menu().
 */
function gsb_node_modal_menu() {
  $items = array();

  $items['gsb-node/%ctools_js/add/%'] = array(
    'title' => 'Create new node',
    'page callback' => 'gsb_node_modal_add',
    'page arguments' => array(1, 3),
    'access callback' => 'node_access',
    'access arguments' => array('create', 3),
  );
  $items['gsb-node/%ctools_js/edit/%node'] = array(
    'title callback' => 'node_page_title',
    'title arguments' => array(3),
    'page callback' => 'gsb_node_modal_edit',
    'page arguments' => array(1, 3),
    'access callback' => 'node_access',
    'access arguments' => array('update', 3),
  );
  $items['gsb-node/%ctools_js/%node/clone/confirm'] = array(
    'title callback' => 'node_page_title',
    'title arguments' => array(2),
    'page callback' => 'gsb_node_modal_clone',
    'page arguments' => array(1, 2),
    'access callback' => 'node_access',
    'access arguments' => array('create', 2),
  );
  $items['gsb-node/%ctools_js/delete/%node'] = array(
    'title' => 'Delete node',
    'page callback' => 'gsb_node_modal_delete',
    'page arguments' => array(1, 3),
    'access callback' => 'node_access',
    'access arguments' => array('delete', 3),
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function gsb_node_modal_admin_paths() {
  $paths = array();
  if (variable_get('node_admin_theme')) {
    $paths['gsb-node/*/add/*'] = TRUE;
    $paths['gsb-node/*/edit/*'] = TRUE;
    $paths['gsb-node/*/clone/confirm'] = TRUE;
    $paths['gsb-node/*/delete/*'] = TRUE;
  }
  return $paths;
}

/**
 * Provides the node add form in a modal.
 */
function gsb_node_modal_add($js, $type, $parent_node = NULL) {
  global $user;

  $type_name = node_type_get_name($type);
  drupal_set_title(t('Create @name', array('@name' => $type_name)), PASS_THROUGH);

  $node = (object) array(
    'uid' => $user->uid,
    'name' => (isset($user->name) ? $user->name : ''),
    'type' => $type,
    'language' => LANGUAGE_NONE,
    'gsb_parent_node' => $parent_node,
  );

  $form_id = $type . '_node_form';
  return _gsb_node_modal_helper($form_id, $js, $node);
}

/**
 * Provides the node edit form in a modal.
 */
function gsb_node_modal_edit($js, $node) {
  $type_name = node_type_get_name($node);
  drupal_set_title(t('<em>Edit @type</em> @title', array('@type' => $type_name, '@title' => $node->title)), PASS_THROUGH);
  $form_id = $node->type . '_node_form';
  return _gsb_node_modal_helper($form_id, $js, $node);
}

/**
 * Provides the node clone form in a modal.
 */
function gsb_node_modal_clone($js, $node) {
  $type_name = node_type_get_name($node);
  drupal_set_title(t('<em>Clone @type</em> @title', array('@type' => $type_name, '@title' => $node->title)), PASS_THROUGH);
  $form_id = $node->type . '_node_form';
  return _gsb_node_modal_helper($form_id, $js, $node);
}

/**
 * Provides the node delete form in a modal.
 */
function gsb_node_modal_delete($js, $node) {
  return _gsb_node_modal_helper('node_delete_confirm', $js, $node);
}

/**
 * Returns a modal node form.
 *
 * @param string $form_id
 *   The form ID to render in the modal.
 * @param bool $js
 *   TRUE if this is an AJAX form, FALSE otherwise.
 * @param object $node
 *   The node object
 *
 * @return array|null
 *   If $js is FALSE, the form array. Otherwise, the content will be output
 *   directly and exit() is called.
 */
function _gsb_node_modal_helper($form_id, $js, $node) {
  $form_state['gsb_node_modal'] = TRUE;
  $form_state['ajax'] = $js;
  $form_state['build_info']['args'] = array($node);
  // Set cache to TRUE so we can process it for AJAX submissions later.
  $form_state['cache'] = TRUE;
  form_load_include($form_state, 'inc', 'node', 'node.pages');

  // If this form was already submitted, track the used HTML IDs.
  if (!empty($_POST['form_build_id'])) {
    list($ajax_form, $ajax_form_state, $ajax_form_id) = ajax_get_form();
    if ($form_id == $ajax_form_id && !empty($ajax_form_state['ajax_html_ids'])) {
      $_POST['ajax_html_ids'] = $ajax_form_state['ajax_html_ids'];
    }
  }

  // If the HTML IDs are being tracked, store them in the form state.
  if (!empty($_POST['ajax_html_ids'])) {
    $form_state['ajax_html_ids'] = $_POST['ajax_html_ids'];
  }

  ctools_include('modal');
  $output = ctools_modal_form_wrapper($form_id, $form_state);
  if (!$js) {
    return $output;
  }

  $commands = $output;
  // If a button executes the form but also flags the form to be rebuilt, do not
  // treat it as an actual form submission, and do not close the modal.
  if (!empty($form_state['executed']) && !$form_state['rebuild']) {
    ctools_include('ajax');
    ctools_add_js('gsb_node_modal', 'gsb_node_modal');
    $commands = array();
    // If there are status messages, print them.
    if ($messages = theme('status_messages')) {
      $commands[] = ajax_command_html('#console', $messages);
    }
    // Reload the view.
    $commands[] = array(
      'command' => 'gsb_node_modal_reload',
    );
    // Close the modal.
    $commands[] = ctools_modal_command_dismiss();
  }
  print ajax_render($commands);
  exit();
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 */
function gsb_node_modal_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form_state['gsb_node_modal']) && isset($form['actions']['delete'])) {
    $form['actions']['delete']['#access'] = FALSE;
  }
}

/**
 * Creates a link to open a node add form in a modal.
 *
 * @param string $text
 *   The translated text to use for the link.
 * @param string $type
 *   The machine name of the content type.
 * @param int $nid
 *   (optional) The node ID of the parent node.
 *
 * @return string
 *   The link to open a node add form in a modal.
 */
function gsb_node_modal_add_link($text, $type, $nid = NULL) {
  $link = 'gsb-node/nojs/add/' . $type;
  // If a parent node was specified, append it to the link.
  if ($nid) {
    $link .= '/' . $nid;
  }
  return _gsb_node_modal_link($text, $link);
}

/**
 * Creates a link to open a node edit form in a modal.
 *
 * @param string $text
 *   The translated text to use for the link.
 * @param int $nid
 *   The node ID to edit.
 *
 * @return string
 *   The link to open a node edit form in a modal.
 */
function gsb_node_modal_edit_link($text, $nid) {
  return _gsb_node_modal_link($text, 'gsb-node/nojs/edit/' . $nid);
}

/**
 * Creates a link to open a node clone form in a modal.
 *
 * @param string $text
 *   The translated text to use for the link.
 * @param int $nid
 *   The node ID to clone.
 *
 * @return string
 *   The link to open a node edit form in a modal.
 */
function gsb_node_modal_clone_link($text, $nid) {
 // return _gsb_node_modal_link($text, 'gsb-node/nojs/clone/' . $nid);
  return _gsb_node_modal_link($text, 'gsb-node/nojs/'. $nid . '/clone/confirm' );
}
/**
 * Helper function for creating a modal link.
 *
 * @param string $text
 *   The translated text to use for the link.
 * @param string $url
 *   The URL for the link.
 *
 * @return string
 *   The link.
 */
function _gsb_node_modal_link($text, $url) {
  ctools_include('ajax');
  ctools_include('modal');
  ctools_modal_add_js();
  return ctools_modal_text_button($text, $url, $text);
}

/**
 * Implements hook_views_api().
 */
function gsb_node_modal_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_data().
 */
function gsb_node_modal_views_data() {
  $data = array();
  $data['views_entity_node']['edit_node_modal'] = array(
    'field' => array(
      'title' => t('Edit link (in modal)'),
      'help' => t('Provide a link to edit the content in a modal.'),
      'handler' => 'gsb_node_modal_handler_field_node_link_edit',
    ),
  );
  $data['views_entity_node']['clone_node_modal'] = array(
    'field' => array(
      'title' => t('Clone link (in modal)'),
      'help' => t('Provide a link to clone the content in a modal.'),
      'handler' => 'gsb_node_modal_handler_field_node_link_clone',
    ),
  );
  $data['views_entity_node']['delete_node_modal'] = array(
    'field' => array(
      'title' => t('Delete link (in modal)'),
      'help' => t('Provide a link to delete the content in a modal.'),
      'handler' => 'gsb_node_modal_handler_field_node_link_delete',
    ),
  );

  $data['gsb__global']['table']['group'] = t('GSB');
  $data['gsb__global']['table']['join']['#global'] = array();
  $data['gsb__global']['gsb_node_modal_add_link'] = array(
    'title' => t('Modal node add link'),
    'help' => t('Displays a link to create a new node in a modal.'),
    'area' => array(
      'handler' => 'gsb_node_modal_handler_area_node_add_link',
    ),
  );
  return $data;
}
